server:
  port: 8080

spring:
  mvc:
    favicon:
      enabled: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false
    enabled: true
  servlet:
    multipart:
      max-file-size: 52428800
      max-request-size: 52428800
  redis:
          #redis数据库地址
          host: localhost
          port: 6379
          password: root
          timeout: 1000
          #redis数据库索引，默认0
          database: 1
  #smtp settings
  mail:
    port: 25
    host:
    username:
    password:
    default-encoding: UTF-8
    protocol: smtp
    test-connection: false

mybatis:
  mapper-locations: classpath:com/my/**/mapper/*.xml
  type-aliases-package: com.my.*.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#pagehelper分页插件
#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql


#file upload
debug: false

#自定义变量
formtool:
  weburl: http://localhost:8080/form/
sitepage:
  weburl: http://localhost:8080/sitepage/
emailread:
  backurl: http://localhost:8080/emailread
blog:
  weburl: http://localhost:8080/blog/
list:
  pagesize: 15
file:
  save-path: E:/upload
  email-image-path: E:/upload/email

#smtp配置
smtp:
  sender:

#session
admin:
  session: ADMIN_SESSION
  account: ADMIN_ACCOUNT
  group: ADMIN_GROUP
  auth: ADMIN_AUTH
  id: ADMIN_ID
login:
  vercode: VERCODE

#日志配置
logging:
  file: E:/log/projects.log
